### PR TITLE
Change default note sort order

### PR DESCRIPTION
**Pull request by kabouzeid**
This or whatever the `zk` default sort order for `zk list` is makes more sense I think

### CODE REVIEW

**Comment by mickael-menu** [comment]
I think we might want to use the default sort value for `zk list`, because it changes depending on the given criteria. I also think it could be useful to be able to customize the default in the `zk` configuration file, per note group. For example you might want to sort by title for an archive folder but by date for a daily journal one.

**Comment by kabouzeid** [comment]
yeah makes sense. how do I get the default `zk list` sort order?

**Comment by mickael-menu** [comment]
If you remove the `sort = ` parameter I think that should use the default sort order?

**Comment by kabouzeid** [comment]
You're right. I've removed the sort key now and instead set it in the default keymaps.

**Review by mickael-menu — APPROVED** [review]

**Pull request merged**
